# Generated by Django 2.2.6 on 2019-10-22 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20191022_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='id',
            new_name='prim_id',
        ),
    ]
