# Generated by Django 2.2.6 on 2019-10-22 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20191022_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='prim_id',
            new_name='id',
        ),
    ]
